import { describe, expect, it } from "vitest";
import { toOracle } from "../src/data/exportSQL/oracle.js";
import { toMySQL } from "../src/data/exportSQL/mysqlEnhanced.js";
import { toPostgres } from "../src/data/exportSQL/postgres.js";
import { fromOracle } from "../src/data/importSQL/oracle.js";
import { fromMySQL } from "../src/data/importSQL/mysqlEnhanced.js";
import { fromPostgres } from "../src/data/importSQL/postgres.js";
import { extractGeneratedColumn } from "../src/data/importSQL/common.js";

const field = (id, name, type, extra = {}) => ({
  id, name, type, size: "", notNull: false, primary: false, unique: false,
  increment: false, default: "", comment: "", check: "", ...extra,
});

function lineItems() {
  return {
    name: "Generated",
    tables: [{
      id: "t",
      name: "line_items",
      fields: [
        field("id", "id", "INT", { primary: true, notNull: true, increment: true }),
        field("q", "quantity", "INT", { notNull: true }),
        field("p", "unit_price", "DECIMAL", { size: "10,2", notNull: true }),
        field("s", "subtotal", "DECIMAL", {
          size: "12,2",
          notNull: true,
          default: "0",
          generated: { expression: "quantity * unit_price", stored: true },
        }),
        field("l", "label", "VARCHAR", {
          size: 80,
          comment: "computed AS (text)",
          generated: { expression: "CONCAT('#', id, ' (x', quantity, ')')", stored: false },
        }),
        field("g", "location", "POINT"),
        field("a", "area", "POLYGON"),
      ],
      indices: [],
    }],
    relationships: [],
  };
}

const byName = (result, name) => result.tables[0].fields.find((f) => f.name === name);

describe("generated columns", () => {
  it("parses generated-column clauses with nested parentheses and strings", () => {
    expect(extractGeneratedColumn("DECIMAL(12,2) GENERATED ALWAYS AS (a * (b + 1)) STORED NOT NULL"))
      .toEqual({ expression: "a * (b + 1)", stored: true });
    expect(extractGeneratedColumn("VARCHAR(9) AS (CONCAT(')', x)) VIRTUAL"))
      .toEqual({ expression: "CONCAT(')', x)", stored: false });
    expect(extractGeneratedColumn("INT AS (a + b) PERSISTENT")).toEqual({ expression: "a + b", stored: true });
    expect(extractGeneratedColumn("NUMBER GENERATED BY DEFAULT AS IDENTITY")).toBeNull();
    expect(extractGeneratedColumn("TEXT COMMENT 'x AS (y)'")).toBeNull();
  });

  it("exports MySQL STORED and VIRTUAL columns and round-trips them", () => {
    const sql = toMySQL(lineItems());

    expect(sql).toContain("`subtotal` DECIMAL(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED NOT NULL,");
    expect(sql).toContain("`label` VARCHAR(80) GENERATED ALWAYS AS (CONCAT('#', id, ' (x', quantity, ')')) VIRTUAL COMMENT 'computed AS (text)',");
    expect(sql).not.toContain("DEFAULT 0");

    const result = fromMySQL(sql);
    expect(byName(result, "subtotal")).toMatchObject({
      type: "DECIMAL",
      notNull: true,
      default: "",
      generated: { expression: "quantity * unit_price", stored: true },
    });
    expect(byName(result, "label")).toMatchObject({
      comment: "computed AS (text)",
      generated: { expression: "CONCAT('#', id, ' (x', quantity, ')')", stored: false },
    });
    expect(byName(result, "quantity").generated).toBeUndefined();
  });

  it("exports PostgreSQL STORED columns without SERIAL or DEFAULT", () => {
    const diagram = lineItems();
    diagram.tables[0].fields.push(field("seq", "seq_copy", "INT", {
      increment: true,
      generated: { expression: "id * 10", stored: true },
    }));
    const sql = toPostgres(diagram);

    expect(sql).toContain('"subtotal" NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED NOT NULL,');
    expect(sql).toContain('"label" VARCHAR(80) GENERATED ALWAYS AS (CONCAT(\'#\', id, \' (x\', quantity, \')\')) STORED,');
    expect(sql).toContain('"seq_copy" INTEGER GENERATED ALWAYS AS (id * 10) STORED');

    const result = fromPostgres(sql);
    expect(byName(result, "subtotal").generated).toEqual({ expression: "quantity * unit_price", stored: true });
    expect(byName(result, "seq_copy")).toMatchObject({ increment: false, generated: { expression: "id * 10" } });
  });

  it("exports Oracle virtual columns and SDO_GEOMETRY spatial columns", () => {
    const sql = toOracle(lineItems());

    expect(sql).toContain('"subtotal" NUMBER(12,2) GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL NOT NULL,');
    expect(sql).toContain('"location" SDO_GEOMETRY,');
    expect(sql).toContain('"area" SDO_GEOMETRY');

    const result = fromOracle(sql);
    expect(byName(result, "subtotal")).toMatchObject({
      increment: false,
      default: "",
      generated: { expression: "quantity * unit_price", stored: false },
    });
    expect(byName(result, "id")).toMatchObject({ increment: true });
    expect(byName(result, "id").generated).toBeUndefined();
  });
});

describe("spatial types", () => {
  it.each([
    "GEOMETRY", "POINT", "LINESTRING", "POLYGON",
    "MULTIPOINT", "MULTILINESTRING", "MULTIPOLYGON", "GEOMETRYCOLLECTION",
  ])("keeps MySQL %s columns through export and import", (type) => {
    const diagram = {
      name: "Spatial",
      tables: [{ id: 0, name: "places", fields: [field(0, "shape", type, { notNull: true })], indices: [] }],
      relationships: [],
    };
    const sql = toMySQL(diagram);

    expect(sql).toContain(`\`shape\` ${type} NOT NULL`);
    expect(fromMySQL(sql).tables[0].fields[0]).toMatchObject({ type, notNull: true });
  });
});
